#ifndef OFFSETS_H
#define OFFSETS_H

#include <windows.h>


#define OFFSET_GAME_MANAGER 0x5225280 
#define OFFSET_GAME_RENDERER 0x5225108   
#define OFFSET_PLAYER_MANAGER 0x5212338 

#define OFFSET_GAMERENDERER_ENGINELINK 0xE0
#define OFFSET_ENGINELINK_ENGINE 0x1d8
#define OFFSET_ENGINE_CAMERA 0x8

#define OFFSET_ENTITY_VIEWANGLES 0x1170
#define OFFSET_VIEWANGLES_QUATERNION 0xC0
#define OFFSET_ENTITY_BULLETANGLES 0xFA5431
#define OFFSET_VIEWANGLES_BULLETANGLES 0x134



#define OFFSET_GAME_MANAGER_ENTITY_COUNT 0x1D0
#define OFFSET_GAMEMANAGER_ENTITYLIST 0x1c8 
#define OFFSET_ENTITY_ENTITYINFO 0x28
#define OFFSET_ENTITYINFO_COMPONENTLIST 0xD8
#define OFFSET_COMPONENTLIST_HEALTHCOMPONENT 0x8
#define OFFSET_HEALTHCOMPONENT_HEALTH 0x148

#define OFFSET_CAMERA_VIEWRIGHT 0xD0
#define OFFSET_CAMERA_VIEWUP 0xE0
#define OFFSET_CAMERA_VIEWFORWARD 0xF0
#define OFFSET_CAMERA_VIEWTRANSLATION 0x100
#define OFFSET_CAMERA_VIEWFOVX 0x110
#define OFFSET_CAMERA_VIEWFOVY 0x124

#define OFFSET_ENTITY_SKELETON 0x20
#define OFFSET_SKELETON_HEADPOSITION 0x660			//head
#define OFFSET_SKELETON_PELVISPOSITION 0xFA0		//pelvis
#define OFFSET_SKELETON_CHESTPOSITION 0xFC0			//chest
#define OFFSET_SKELETON_HANDPOSITION 0x6A0			//rhand
#define OFFSET_SKELETON_NECKPOSITION 0xF40			//NECK
#define OFFSET_SKELETON_STOMACHPOSITION 0xF80		//stomach	
#define OFFSET_SKELETON_POSITION 0x6C0				//feet

#define OFFSET_ENTITY_COMPONENT 0x28 
#define OFFSET_ENTITY_COMPONENT_LIST 0xD8 
#define OFFSET_ENTITY_COMPONENT_HEALTH 0x140

#define OFFSET_SPOOF_SPECTATE 0x51B8840    
#define OFFSET_SPOOF_SPECTATE_ENABLE 0x5D

#define OFFSET_ENVIRONMENT_AREA 0x5E99BE0  
#define OFFSET_ENVIRONMENT_AREA_GLOW 0xB8
#define OFFSET_ENVIRONMENT_AREA_GLOW_ON 0x114 
#define OFFSET_ENVIRONMENT_AREA_START_DISTANCE    0x130 
#define OFFSET_ENVIRONMENT_AREA_RELIEF 0x138 

#define OFFSET_STATUS_MANAGER 0x5225220  
#define OFFSET_STATUS_MANAGER_CONTAINER 0x370 
#define OFFSET_STATUS_MANAGER_LOCALENTITY 0x28 

#define ENTITY_MARKER_VT_OFFSET		0x37EC998
#define ENTITY_MARKER_ENABLED_OFFSET 0x530


#define OFFSET_NETWORK_MANAGER                  0x52124C0  
#define OFFSET_ROUND_MANAGER					0x52124B8  
#define OFFSET_FOV_CHANGER						0x5225270  
#define OFFSET_SPEED_MANAGER					0x5017748 

#ifdef _AMD64_
#define _PTR_MAX_VALUE ( 0x000F000000000000 )
#else 
#define _PTR_MAX_VALUE ( 0xFFE00000 )
#endif

inline bool _VALID( UINT_PTR Ptr )
{
	return ( Ptr >= 0x10000 ) && ( Ptr < _PTR_MAX_VALUE );
}

#endif
